version: '3'
services:
  app:
    image: feedback
    build: .
    command: "npm start"
    ports:
     - "4005:4005"
    depends_on:
      - "mongo"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27012:27017'