version: '3'
services:
  app:
    image: admin
    build: .
    command: "npm start"
    ports:
     - "4002:4002"
    depends_on:
      - "mongo"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27012:27017'